### ISSUE TITLE
the code of Figure 1 of the paper

### ISSUE THREAD

**Issue by hongjiangtao** [tkj516/score_based_source_separation#1]
I did not find the code of Figure 1 of the paper, if it is convenient, can you updata the code ?

**Comment by tkj516** [comment]
Hello! Sorry for the late response. I have added the notebook here: https://github.com/tkj516/score_based_source_separation/blob/main/source_separation/notebooks/Toy_Example_Figure_1.ipynb

Hope this helps!

**Comment by hongjiangtao** [comment]
Thank you very much for your help！
